services:

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  web:
    image: keygen/api:latest
    ports:
      - "3000:3000"
    command: "web"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    volumes:
      - keygen:/etc/keygen
    depends_on:
      - postgres
      - redis

  worker:
    image: keygen/api:latest
    command: "worker"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    volumes:
      - keygen:/etc/keygen
    depends_on:
      - postgres
      - redis


volumes:
  keygen:
  postgres:
  redis:
  caddy_data:
  caddy_config:
