services:
  setup:
    profiles: [ "setup" ]
    image: keygen/api:latest
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}"
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    env_file:
      - .env
    command: >
      sh -c "
        until pg_isready -h postgres -U ${POSTGRES_USER}; do
          echo 'Waiting for PostgreSQL...'
          sleep 1
        done
        bundle exec rails keygen:setup
      "
    depends_on: [ postgres ]
    tty: true
    stdin_open: true

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

  web:
    image: keygen/api:latest
    command: "web"
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}"
    volumes:
      - keygen:/etc/keygen
    depends_on:
      - postgres
      - redis

  worker:
    image: keygen/api:latest
    command: "worker"
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}"
    volumes:
      - keygen:/etc/keygen
    depends_on:
      - postgres
      - redis


volumes:
  keygen:
  postgres:
  redis: